export const currencies = [
    { code: "INR", symbol: "₹", name: "Indian Rupee" },
    { code: "AED", symbol: "د.إ", name: "United Arab Emirates Dirham" },
    { code: "AFN", symbol: "؋", name: "Afghan Afghani" },
    { code: "ALL", symbol: "L", name: "Albanian Lek" },
    { code: "AMD", symbol: "֏", name: "Armenian Dram" },
    { code: "ANG", symbol: "ƒ", name: "Netherlands Antillean Guilder" },
    { code: "AOA", symbol: "Kz", name: "Angolan Kwanza" },
    { code: "ARS", symbol: "$", name: "Argentine Peso" },
    { code: "AUD", symbol: "$", name: "Australian Dollar" },
    { code: "AWG", symbol: "ƒ", name: "Aruban Florin" },
    { code: "AZN", symbol: "₼", name: "Azerbaijani Manat" },
    { code: "BAM", symbol: "KM", name: "Bosnia-Herzegovina Convertible Mark" },
    { code: "BBD", symbol: "$", name: "Barbadian Dollar" },
    { code: "BDT", symbol: "৳", name: "Bangladeshi Taka" },
    { code: "BGN", symbol: "лв", name: "Bulgarian Lev" },
    { code: "BHD", symbol: ".د.ب", name: "Bahraini Dinar" },
    { code: "BIF", symbol: "FBu", name: "Burundian Franc" },
    { code: "BMD", symbol: "$", name: "Bermudan Dollar" },
    { code: "BND", symbol: "$", name: "Brunei Dollar" },
    { code: "BOB", symbol: "Bs.", name: "Bolivian Boliviano" },
    { code: "BRL", symbol: "R$", name: "Brazilian Real" },
    { code: "BSD", symbol: "$", name: "Bahamian Dollar" },
    { code: "BTN", symbol: "Nu.", name: "Bhutanese Ngultrum" },
    { code: "BWP", symbol: "P", name: "Botswana Pula" },
    { code: "BYN", symbol: "Br", name: "Belarusian Ruble" },
    { code: "BZD", symbol: "BZ$", name: "Belize Dollar" },
    { code: "CAD", symbol: "$", name: "Canadian Dollar" },
    { code: "CDF", symbol: "FC", name: "Congolese Franc" },
    { code: "CHF", symbol: "CHF", name: "Swiss Franc" },
    { code: "CLP", symbol: "$", name: "Chilean Peso" },
    { code: "CNY", symbol: "¥", name: "Chinese Yuan" },
    { code: "COP", symbol: "$", name: "Colombian Peso" },
    { code: "CRC", symbol: "₡", name: "Costa Rican Colón" },
    { code: "CUP", symbol: "₱", name: "Cuban Peso" },
    { code: "CVE", symbol: "$", name: "Cape Verdean Escudo" },
    { code: "CZK", symbol: "Kč", name: "Czech Koruna" },
    { code: "DJF", symbol: "Fdj", name: "Djiboutian Franc" },
    { code: "DKK", symbol: "kr", name: "Danish Krone" },
    { code: "DOP", symbol: "RD$", name: "Dominican Peso" },
    { code: "DZD", symbol: "د.ج", name: "Algerian Dinar" },
    { code: "EGP", symbol: "£", name: "Egyptian Pound" },
    { code: "ERN", symbol: "Nfk", name: "Eritrean Nakfa" },
    { code: "ETB", symbol: "Br", name: "Ethiopian Birr" },
    { code: "EUR", symbol: "€", name: "Euro" },
    { code: "FJD", symbol: "$", name: "Fijian Dollar" },
    { code: "FKP", symbol: "£", name: "Falkland Islands Pound" },
    { code: "GBP", symbol: "£", name: "British Pound Sterling" },
    { code: "GEL", symbol: "₾", name: "Georgian Lari" },
    { code: "GHS", symbol: "GH₵", name: "Ghanaian Cedi" },
    { code: "GIP", symbol: "£", name: "Gibraltar Pound" },
    { code: "GMD", symbol: "D", name: "Gambian Dalasi" },
    { code: "GNF", symbol: "FG", name: "Guinean Franc" },
    { code: "GTQ", symbol: "Q", name: "Guatemalan Quetzal" },
    { code: "GYD", symbol: "$", name: "Guyanaese Dollar" },
    { code: "HKD", symbol: "$", name: "Hong Kong Dollar" },
    { code: "HNL", symbol: "L", name: "Honduran Lempira" },
    { code: "HRK", symbol: "kn", name: "Croatian Kuna" },
    { code: "HTG", symbol: "G", name: "Haitian Gourde" },
    { code: "HUF", symbol: "Ft", name: "Hungarian Forint" },
    { code: "IDR", symbol: "Rp", name: "Indonesian Rupiah" },
    { code: "ILS", symbol: "₪", name: "Israeli New Shekel" },
    { code: "INR", symbol: "₹", name: "Indian Rupee" },
    { code: "IQD", symbol: "ع.د", name: "Iraqi Dinar" },
    { code: "IRR", symbol: "﷼", name: "Iranian Rial" },
    { code: "ISK", symbol: "kr", name: "Icelandic Króna" },
    { code: "JMD", symbol: "J$", name: "Jamaican Dollar" },
    { code: "JOD", symbol: "د.ا", name: "Jordanian Dinar" },
    { code: "JPY", symbol: "¥", name: "Japanese Yen" },
    { code: "KES", symbol: "KSh", name: "Kenyan Shilling" },
    { code: "KGS", symbol: "с", name: "Kyrgystani Som" },
    { code: "KHR", symbol: "៛", name: "Cambodian Riel" },
    { code: "KMF", symbol: "CF", name: "Comorian Franc" },
    { code: "KPW", symbol: "₩", name: "North Korean Won" },
    { code: "KRW", symbol: "₩", name: "South Korean Won" },
    { code: "KWD", symbol: "د.ك", name: "Kuwaiti Dinar" },
    { code: "KYD", symbol: "$", name: "Cayman Islands Dollar" },
    { code: "KZT", symbol: "₸", name: "Kazakhstani Tenge" },
    { code: "LAK", symbol: "₭", name: "Laotian Kip" },
    { code: "LBP", symbol: "L£", name: "Lebanese Pound" },
    { code: "LKR", symbol: "Rs", name: "Sri Lankan Rupee" },
    { code: "LRD", symbol: "$", name: "Liberian Dollar" },
    { code: "LSL", symbol: "L", name: "Lesotho Loti" },
    { code: "LYD", symbol: "ل.د", name: "Libyan Dinar" },
    { code: "MAD", symbol: "dh", name: "Moroccan Dirham" },
    { code: "MDL", symbol: "L", name: "Moldovan Leu" },
    { code: "MGA", symbol: "Ar", name: "Malagasy Ariary" },
    { code: "MKD", symbol: "ден", name: "Macedonian Denar" },
    { code: "MMK", symbol: "K", name: "Myanma Kyat" },
    { code: "MNT", symbol: "₮", name: "Mongolian Tugrik" },
    { code: "MOP", symbol: "MOP$", name: "Macanese Pataca" },
    { code: "MRU", symbol: "UM", name: "Mauritanian Ouguiya" },
    { code: "MUR", symbol: "₨", name: "Mauritian Rupee" },
    { code: "MVR", symbol: "Rf", name: "Maldivian Rufiyaa" },
    { code: "MWK", symbol: "MK", name: "Malawian Kwacha" },
    { code: "MXN", symbol: "$", name: "Mexican Peso" },
    { code: "MYR", symbol: "RM", name: "Malaysian Ringgit" },
    { code: "MZN", symbol: "MT", name: "Mozambican Metical" },
    { code: "NAD", symbol: "$", name: "Namibian Dollar" },
    { code: "NGN", symbol: "₦", name: "Nigerian Naira" },
    { code: "NIO", symbol: "C$", name: "Nicaraguan Córdoba" },
    { code: "NOK", symbol: "kr", name: "Norwegian Krone" },
    { code: "NPR", symbol: "₨", name: "Nepalese Rupee" },
    { code: "NZD", symbol: "$", name: "New Zealand Dollar" },
    { code: "OMR", symbol: "ر.ع.", name: "Omani Rial" },
    { code: "PAB", symbol: "B/.", name: "Panamanian Balboa" },
    { code: "PEN", symbol: "S/", name: "Peruvian Sol" },
    { code: "PGK", symbol: "K", name: "Papua New Guinean Kina" },
    { code: "PHP", symbol: "₱", name: "Philippine Peso" },
    { code: "PKR", symbol: "₨", name: "Pakistani Rupee" },
    { code: "PLN", symbol: "zł", name: "Polish Zloty" },
    { code: "PYG", symbol: "₲", name: "Paraguayan Guarani" },
    { code: "QAR", symbol: "ر.ق", name: "Qatari Rial" },
    { code: "RON", symbol: "lei", name: "Romanian Leu" },
    { code: "RSD", symbol: "дин.", name: "Serbian Dinar" },
    { code: "RUB", symbol: "₽", name: "Russian Ruble" },
    { code: "RWF", symbol: "FRw", name: "Rwandan Franc" },
    { code: "SAR", symbol: "﷼", name: "Saudi Riyal" },
    { code: "SBD", symbol: "$", name: "Solomon Islands Dollar" },
    { code: "SCR", symbol: "₨", name: "Seychellois Rupee" },
    { code: "SDG", symbol: "ج.س.", name: "Sudanese Pound" },
    { code: "SEK", symbol: "kr", name: "Swedish Krona" },
    { code: "SGD", symbol: "$", name: "Singapore Dollar" },
    { code: "SHP", symbol: "£", name: "Saint Helena Pound" },
    { code: "SLL", symbol: "Le", name: "Sierra Leonean Leone" },
    { code: "SOS", symbol: "S", name: "Somali Shilling" },
    { code: "SRD", symbol: "$", name: "Surinamese Dollar" },
    { code: "SSP", symbol: "£", name: "South Sudanese Pound" },
    { code: "STN", symbol: "Db", name: "São Tomé and Príncipe Dobra" },
    { code: "SYP", symbol: "£", name: "Syrian Pound" },
    { code: "SZL", symbol: "L", name: "Swazi Lilangeni" },
    { code: "THB", symbol: "฿", name: "Thai Baht" },
    { code: "TJS", symbol: "SM", name: "Tajikistani Somoni" },
    { code: "TMT", symbol: "T", name: "Turkmenistani Manat" },
    { code: "TND", symbol: "د.ت", name: "Tunisian Dinar" },
    { code: "TOP", symbol: "T$", name: "Tongan Paʻanga" },
    { code: "TRY", symbol: "₺", name: "Turkish Lira" },
    { code: "TTD", symbol: "TT$", name: "Trinidad and Tobago Dollar" },
    { code: "TWD", symbol: "NT$", name: "New Taiwan Dollar" },
    { code: "TZS", symbol: "TSh", name: "Tanzanian Shilling" },
    { code: "UAH", symbol: "₴", name: "Ukrainian Hryvnia" },
    { code: "UGX", symbol: "USh", name: "Ugandan Shilling" },
    { code: "USD", symbol: "$", name: "United States Dollar" },
    { code: "UYU", symbol: "$U", name: "Uruguayan Peso" },
    { code: "UZS", symbol: "лв", name: "Uzbekistan Som" },
    { code: "VES", symbol: "Bs.S", name: "Venezuelan Bolívar Soberano" },
    { code: "VND", symbol: "₫", name: "Vietnamese Dong" },
    { code: "VUV", symbol: "VT", name: "Vanuatu Vatu" },
    { code: "WST", symbol: "T", name: "Samoan Tala" },
    { code: "XAF", symbol: "FCFA", name: "CFA Franc BEAC" },
    { code: "XCD", symbol: "$", name: "East Caribbean Dollar" },
    { code: "XOF", symbol: "CFA", name: "CFA Franc BCEAO" },
    { code: "XPF", symbol: "₣", name: "CFP Franc" },
    { code: "YER", symbol: "﷼", name: "Yemeni Rial" },
    { code: "ZAR", symbol: "R", name: "South African Rand" },
    { code: "ZMW", symbol: "ZK", name: "Zambian Kwacha" },
    { code: "ZWL", symbol: "$", name: "Zimbabwean Dollar" }
];

export const countryCodes = [{
    code: "IN", dial_code: "+91", name: "India"
},
{ code: "AF", dial_code: "+93", name: "Afghanistan" },
{ code: "AL", dial_code: "+355", name: "Albania" },
{ code: "DZ", dial_code: "+213", name: "Algeria" },
{ code: "AS", dial_code: "+1-684", name: "American Samoa" },
{ code: "AD", dial_code: "+376", name: "Andorra" },
{ code: "AO", dial_code: "+244", name: "Angola" },
{ code: "AI", dial_code: "+1-264", name: "Anguilla" },
{ code: "AQ", dial_code: "+672", name: "Antarctica" },
{ code: "AG", dial_code: "+1-268", name: "Antigua and Barbuda" },
{ code: "AR", dial_code: "+54", name: "Argentina" },
{ code: "AM", dial_code: "+374", name: "Armenia" },
{ code: "AW", dial_code: "+297", name: "Aruba" },
{ code: "AU", dial_code: "+61", name: "Australia" },
{ code: "AT", dial_code: "+43", name: "Austria" },
{ code: "AZ", dial_code: "+994", name: "Azerbaijan" },
{ code: "BS", dial_code: "+1-242", name: "Bahamas" },
{ code: "BH", dial_code: "+973", name: "Bahrain" },
{ code: "BD", dial_code: "+880", name: "Bangladesh" },
{ code: "BB", dial_code: "+1-246", name: "Barbados" },
{ code: "BY", dial_code: "+375", name: "Belarus" },
{ code: "BE", dial_code: "+32", name: "Belgium" },
{ code: "BZ", dial_code: "+501", name: "Belize" },
{ code: "BJ", dial_code: "+229", name: "Benin" },
{ code: "BM", dial_code: "+1-441", name: "Bermuda" },
{ code: "BT", dial_code: "+975", name: "Bhutan" },
{ code: "BO", dial_code: "+591", name: "Bolivia" },
{ code: "BA", dial_code: "+387", name: "Bosnia and Herzegovina" },
{ code: "BW", dial_code: "+267", name: "Botswana" },
{ code: "BR", dial_code: "+55", name: "Brazil" },
{ code: "IO", dial_code: "+246", name: "British Indian Ocean Territory" },
{ code: "VG", dial_code: "+1-284", name: "British Virgin Islands" },
{ code: "BN", dial_code: "+673", name: "Brunei" },
{ code: "BG", dial_code: "+359", name: "Bulgaria" },
{ code: "BF", dial_code: "+226", name: "Burkina Faso" },
{ code: "BI", dial_code: "+257", name: "Burundi" },
{ code: "KH", dial_code: "+855", name: "Cambodia" },
{ code: "CM", dial_code: "+237", name: "Cameroon" },
{ code: "CA", dial_code: "+1", name: "Canada" },
{ code: "CV", dial_code: "+238", name: "Cape Verde" },
{ code: "KY", dial_code: "+1-345", name: "Cayman Islands" },
{ code: "CF", dial_code: "+236", name: "Central African Republic" },
{ code: "TD", dial_code: "+235", name: "Chad" },
{ code: "CL", dial_code: "+56", name: "Chile" },
{ code: "CN", dial_code: "+86", name: "China" },
{ code: "CX", dial_code: "+61", name: "Christmas Island" },
{ code: "CC", dial_code: "+61", name: "Cocos Islands" },
{ code: "CO", dial_code: "+57", name: "Colombia" },
{ code: "KM", dial_code: "+269", name: "Comoros" },
{ code: "CK", dial_code: "+682", name: "Cook Islands" },
{ code: "CR", dial_code: "+506", name: "Costa Rica" },
{ code: "HR", dial_code: "+385", name: "Croatia" },
{ code: "CU", dial_code: "+53", name: "Cuba" },
{ code: "CW", dial_code: "+599", name: "Curacao" },
{ code: "CY", dial_code: "+357", name: "Cyprus" },
{ code: "CZ", dial_code: "+420", name: "Czech Republic" },
{ code: "CD", dial_code: "+243", name: "Democratic Republic of the Congo" },
{ code: "DK", dial_code: "+45", name: "Denmark" },
{ code: "DJ", dial_code: "+253", name: "Djibouti" },
{ code: "DM", dial_code: "+1-767", name: "Dominica" },
{ code: "DO", dial_code: "+1-809, 1-829, 1-849", name: "Dominican Republic" },
{ code: "TL", dial_code: "+670", name: "East Timor" },
{ code: "EC", dial_code: "+593", name: "Ecuador" },
{ code: "EG", dial_code: "+20", name: "Egypt" },
{ code: "SV", dial_code: "+503", name: "El Salvador" },
{ code: "GQ", dial_code: "+240", name: "Equatorial Guinea" },
{ code: "ER", dial_code: "+291", name: "Eritrea" },
{ code: "EE", dial_code: "+372", name: "Estonia" },
{ code: "ET", dial_code: "+251", name: "Ethiopia" },
{ code: "FK", dial_code: "+500", name: "Falkland Islands" },
{ code: "FO", dial_code: "+298", name: "Faroe Islands" },
{ code: "FJ", dial_code: "+679", name: "Fiji" },
{ code: "FI", dial_code: "+358", name: "Finland" },
{ code: "FR", dial_code: "+33", name: "France" },
{ code: "PF", dial_code: "+689", name: "French Polynesia" },
{ code: "GA", dial_code: "+241", name: "Gabon" },
{ code: "GM", dial_code: "+220", name: "Gambia" },
{ code: "GE", dial_code: "+995", name: "Georgia" },
{ code: "DE", dial_code: "+49", name: "Germany" },
{ code: "GH", dial_code: "+233", name: "Ghana" },
{ code: "GI", dial_code: "+350", name: "Gibraltar" },
{ code: "GR", dial_code: "+30", name: "Greece" },
{ code: "GL", dial_code: "+299", name: "Greenland" },
{ code: "GD", dial_code: "+1-473", name: "Grenada" },
{ code: "GU", dial_code: "+1-671", name: "Guam" },
{ code: "GT", dial_code: "+502", name: "Guatemala" },
{ code: "GG", dial_code: "+44-1481", name: "Guernsey" },
{ code: "GN", dial_code: "+224", name: "Guinea" },
{ code: "GW", dial_code: "+245", name: "Guinea-Bissau" },
{ code: "GY", dial_code: "+592", name: "Guyana" },
{ code: "HT", dial_code: "+509", name: "Haiti" },
{ code: "HN", dial_code: "+504", name: "Honduras" },
{ code: "HK", dial_code: "+852", name: "Hong Kong" },
{ code: "HU", dial_code: "+36", name: "Hungary" },
{ code: "IS", dial_code: "+354", name: "Iceland" },

{ code: "ID", dial_code: "+62", name: "Indonesia" },
{ code: "IR", dial_code: "+98", name: "Iran" },
{ code: "IQ", dial_code: "+964", name: "Iraq" },
{ code: "IE", dial_code: "+353", name: "Ireland" },
{ code: "IM", dial_code: "+44-1624", name: "Isle of Man" },
{ code: "IL", dial_code: "+972", name: "Israel" },
{ code: "IT", dial_code: "+39", name: "Italy" },
{ code: "CI", dial_code: "+225", name: "Ivory Coast" },
{ code: "JM", dial_code: "+1-876", name: "Jamaica" },
{ code: "JP", dial_code: "+81", name: "Japan" },
{ code: "JE", dial_code: "+44-1534", name: "Jersey" },
{ code: "JO", dial_code: "+962", name: "Jordan" },
{ code: "KZ", dial_code: "+7", name: "Kazakhstan" },
{ code: "KE", dial_code: "+254", name: "Kenya" },
{ code: "KI", dial_code: "+686", name: "Kiribati" },
{ code: "XK", dial_code: "+383", name: "Kosovo" },
{ code: "KW", dial_code: "+965", name: "Kuwait" },
{ code: "KG", dial_code: "+996", name: "Kyrgyzstan" },
{ code: "LA", dial_code: "+856", name: "Laos" },
{ code: "LV", dial_code: "+371", name: "Latvia" },
{ code: "LB", dial_code: "+961", name: "Lebanon" },
{ code: "LS", dial_code: "+266", name: "Lesotho" },
{ code: "LR", dial_code: "+231", name: "Liberia" },
{ code: "LY", dial_code: "+218", name: "Libya" },
{ code: "LI", dial_code: "+423", name: "Liechtenstein" },
{ code: "LT", dial_code: "+370", name: "Lithuania" },
{ code: "LU", dial_code: "+352", name: "Luxembourg" },
{ code: "MO", dial_code: "+853", name: "Macau" },
{ code: "MK", dial_code: "+389", name: "Macedonia" },
{ code: "MG", dial_code: "+261", name: "Madagascar" },
{ code: "MW", dial_code: "+265", name: "Malawi" },
{ code: "MY", dial_code: "+60", name: "Malaysia" },
{ code: "MV", dial_code: "+960", name: "Maldives" },
{ code: "ML", dial_code: "+223", name: "Mali" },
{ code: "MT", dial_code: "+356", name: "Malta" },
{ code: "MH", dial_code: "+692", name: "Marshall Islands" },
{ code: "MR", dial_code: "+222", name: "Mauritania" },
{ code: "MU", dial_code: "+230", name: "Mauritius" },
{ code: "YT", dial_code: "+262", name: "Mayotte" },
{ code: "MX", dial_code: "+52", name: "Mexico" },
{ code: "FM", dial_code: "+691", name: "Micronesia" },
{ code: "MD", dial_code: "+373", name: "Moldova" },
{ code: "MC", dial_code: "+377", name: "Monaco" },
{ code: "MN", dial_code: "+976", name: "Mongolia" },
{ code: "ME", dial_code: "+382", name: "Montenegro" },
{ code: "MS", dial_code: "+1-664", name: "Montserrat" },
{ code: "MA", dial_code: "+212", name: "Morocco" },
{ code: "MZ", dial_code: "+258", name: "Mozambique" },
{ code: "MM", dial_code: "+95", name: "Myanmar" },
{ code: "NA", dial_code: "+264", name: "Namibia" },
{ code: "NR", dial_code: "+674", name: "Nauru" },
{ code: "NP", dial_code: "+977", name: "Nepal" },
{ code: "NL", dial_code: "+31", name: "Netherlands" },
{ code: "AN", dial_code: "+599", name: "Netherlands Antilles" },
{ code: "NC", dial_code: "+687", name: "New Caledonia" },
{ code: "NZ", dial_code: "+64", name: "New Zealand" },
{ code: "NI", dial_code: "+505", name: "Nicaragua" },
{ code: "NE", dial_code: "+227", name: "Niger" },
{ code: "NG", dial_code: "+234", name: "Nigeria" },
{ code: "NU", dial_code: "+683", name: "Niue" },
{ code: "KP", dial_code: "+850", name: "North Korea" },
{ code: "MP", dial_code: "+1-670", name: "Northern Mariana Islands" },
{ code: "NO", dial_code: "+47", name: "Norway" },
{ code: "OM", dial_code: "+968", name: "Oman" },
{ code: "PK", dial_code: "+92", name: "Pakistan" },
{ code: "PW", dial_code: "+680", name: "Palau" },
{ code: "PS", dial_code: "+970", name: "Palestine" },
{ code: "PA", dial_code: "+507", name: "Panama" },
{ code: "PG", dial_code: "+675", name: "Papua New Guinea" },
{ code: "PY", dial_code: "+595", name: "Paraguay" },
{ code: "PE", dial_code: "+51", name: "Peru" },
{ code: "PH", dial_code: "+63", name: "Philippines" },
{ code: "PN", dial_code: "+870", name: "Pitcairn" },
{ code: "PL", dial_code: "+48", name: "Poland" },
{ code: "PT", dial_code: "+351", name: "Portugal" },
{ code: "PR", dial_code: "+1-787, 1-939", name: "Puerto Rico" },
{ code: "QA", dial_code: "+974", name: "Qatar" },
{ code: "CG", dial_code: "+242", name: "Republic of the Congo" },
{ code: "RE", dial_code: "+262", name: "Reunion" },
{ code: "RO", dial_code: "+40", name: "Romania" },
{ code: "RU", dial_code: "+7", name: "Russia" },
{ code: "RW", dial_code: "+250", name: "Rwanda" },
{ code: "BL", dial_code: "+590", name: "Saint Barthelemy" },
{ code: "SH", dial_code: "+290", name: "Saint Helena" },
{ code: "KN", dial_code: "+1-869", name: "Saint Kitts and Nevis" },
{ code: "LC", dial_code: "+1-758", name: "Saint Lucia" },
{ code: "MF", dial_code: "+590", name: "Saint Martin" },
{ code: "PM", dial_code: "+508", name: "Saint Pierre and Miquelon" },
{ code: "VC", dial_code: "+1-784", name: "Saint Vincent and the Grenadines" },
{ code: "WS", dial_code: "+685", name: "Samoa" },
{ code: "SM", dial_code: "+378", name: "San Marino" },
{ code: "ST", dial_code: "+239", name: "Sao Tome and Principe" },
{ code: "SA", dial_code: "+966", name: "Saudi Arabia" },
{ code: "SN", dial_code: "+221", name: "Senegal" },
{ code: "RS", dial_code: "+381", name: "Serbia" },
{ code: "SC", dial_code: "+248", name: "Seychelles" },
{ code: "SL", dial_code: "+232", name: "Sierra Leone" },
{ code: "SG", dial_code: "+65", name: "Singapore" },
{ code: "SX", dial_code: "+1-721", name: "Sint Maarten" },
{ code: "SK", dial_code: "+421", name: "Slovakia" },
{ code: "SI", dial_code: "+386", name: "Slovenia" },
{ code: "SB", dial_code: "+677", name: "Solomon Islands" },
{ code: "SO", dial_code: "+252", name: "Somalia" },
{ code: "ZA", dial_code: "+27", name: "South Africa" },
{ code: "KR", dial_code: "+82", name: "South Korea" },
{ code: "SS", dial_code: "+211", name: "South Sudan" },
{ code: "ES", dial_code: "+34", name: "Spain" },
{ code: "LK", dial_code: "+94", name: "Sri Lanka" },
{ code: "SD", dial_code: "+249", name: "Sudan" },
{ code: "SR", dial_code: "+597", name: "Suriname" },
{ code: "SJ", dial_code: "+47", name: "Svalbard and Jan Mayen" },
{ code: "SZ", dial_code: "+268", name: "Swaziland" },
{ code: "SE", dial_code: "+46", name: "Sweden" },
{ code: "CH", dial_code: "+41", name: "Switzerland" },
{ code: "SY", dial_code: "+963", name: "Syria" },
{ code: "TW", dial_code: "+886", name: "Taiwan" },
{ code: "TJ", dial_code: "+992", name: "Tajikistan" },
{ code: "TZ", dial_code: "+255", name: "Tanzania" },
{ code: "TH", dial_code: "+66", name: "Thailand" },
{ code: "TG", dial_code: "+228", name: "Togo" },
{ code: "TK", dial_code: "+690", name: "Tokelau" },
{ code: "TO", dial_code: "+676", name: "Tonga" },
{ code: "TT", dial_code: "+1-868", name: "Trinidad and Tobago" },
{ code: "TN", dial_code: "+216", name: "Tunisia" },
{ code: "TR", dial_code: "+90", name: "Turkey" },
{ code: "TM", dial_code: "+993", name: "Turkmenistan" },
{ code: "TC", dial_code: "+1-649", name: "Turks and Caicos Islands" },
{ code: "TV", dial_code: "+688", name: "Tuvalu" },
{ code: "VI", dial_code: "+1-340", name: "U.S. Virgin Islands" },
{ code: "UG", dial_code: "+256", name: "Uganda" },
{ code: "UA", dial_code: "+380", name: "Ukraine" },
{ code: "AE", dial_code: "+971", name: "United Arab Emirates" },
{ code: "GB", dial_code: "+44", name: "United Kingdom" },
{ code: "US", dial_code: "+1", name: "United States" },
{ code: "UY", dial_code: "+598", name: "Uruguay" },
{ code: "UZ", dial_code: "+998", name: "Uzbekistan" },
{ code: "VU", dial_code: "+678", name: "Vanuatu" },
{ code: "VA", dial_code: "+379", name: "Vatican" },
{ code: "VE", dial_code: "+58", name: "Venezuela" },
{ code: "VN", dial_code: "+84", name: "Vietnam" },
{ code: "WF", dial_code: "+681", name: "Wallis and Futuna" },
{ code: "EH", dial_code: "+212", name: "Western Sahara" },
{ code: "YE", dial_code: "+967", name: "Yemen" },
{ code: "ZM", dial_code: "+260", name: "Zambia" },
{ code: "ZW", dial_code: "+263", name: "Zimbabwe" },
];
